base_learning_rate: 0.001
batch_size: 8
callback_list: checkpoint, csv_log
fixed: false
gpus: 1
model_dir: ../models/mobilenetv2_48594573_2023-08-11_14-04-59/
model_type: mobilenetv2
nodes: 1
num_classes: 8
num_epochs: 50
optimizer: sgd
test_dir: /data/cs4321/HW1/test
train_dir: /data/cs4321/HW1/train
unfreeze: 8
val_dir: /data/cs4321/HW1/validation
world_size: 1
