activation_fn: relu
base_learning_rate: 0.001
batch_size: 32
callback_list: checkpoint, csv_log
checkpoint_path: null
continue_training: false
eval_metrics: accuracy
gpus: 1
input_shape: !!python/tuple
- 28
- 28
loss_type: categorical_crossentropy
mgpu_run: false
model_dir: /home/madina.petashvili/team_hp_cs4321_midterm/models/mobilenetv2_2023-08-10_21-34-44/
model_type: mobilenetv2
nodes: 1
num_classes: 8
num_epochs: 40
optimizer: adam
predict: false
regression: false
test_dir: /data/cs4321/HW1/test
train_dir: /data/cs4321/HW1/train
unfreeze: 2
use_multiprocessing: true
val_dir: /data/cs4321/HW1/validation
workers: 6
world_size: 1
